schema = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 3

[[blocks]]
alignment = "left"
type = "prompt"

[[blocks.segments]]
background = "#292929"
foreground = "#fb7e14"
leading_diamond = "\ue0b6"
trailing_diamond = "\uE0B0"
style = "diamond"
template = " {{ .Path }} "
type = "path"

[blocks.segments.properties]
style = "folder"

[[blocks.segments]]
background = "#292929"
foreground = "#fb7e14"
leading_diamond = "<transparent,background>\uE0B0</>"
trailing_diamond = "\uE0B0"
style = "diamond"
template = " {{ .HEAD }} "
type = "git"


[blocks.segments.properties]
branch_icon = "\ue725 "
fetch_status = true
fetch_upstream_icon = true
style = "diamond"
display_mode = "files"
fetch_virtual_env = false

background_templates = [
    "{{ if or (.Working.Changed) (.Staging.Changed) }}#292929{{ end }}",
    "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#FFCC80{{ end }}",
    "{{ if gt .Ahead 0 }}#292929{{ end }}",
    "{{ if gt .Behind 0 }}#292929{{ end }}"
]

